## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
arr = np.arange(10)
index = np.where((arr > 3) & (arr < 8))
print('Исходный массив', arr)
arr[index] = -arr[index]
print('Итоговый массив', arr)

Исходный массив [0 1 2 3 4 5 6 7 8 9]
Итоговый массив [ 0  1  2  3 -4 -5 -6 -7  8  9]


**2.** Заменить максимальный элемент случайного массива на 0

In [3]:
arr = np.random.randint(1, 100, 15)
print("Исходный массив", arr)
max_arr_elem = arr.max()
index = arr == max_arr_elem
arr[index] = 0
print('Итоговый маассив', arr)

Исходный массив [20 33 95 64 32  4 38 71 81 59 75 82 69 18  1]
Итоговый маассив [20 33  0 64 32  4 38 71 81 59 75 82 69 18  1]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [4]:
# с использование стандартной библиотеки itertools
from itertools import product
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = np.array(list(product(*arr)))
print('Прямое произведение векторов двумерного массива', result, sep='\n')

Прямое произведение векторов двумерного массива
[[1 4 7]
 [1 4 8]
 [1 4 9]
 [1 5 7]
 [1 5 8]
 [1 5 9]
 [1 6 7]
 [1 6 8]
 [1 6 9]
 [2 4 7]
 [2 4 8]
 [2 4 9]
 [2 5 7]
 [2 5 8]
 [2 5 9]
 [2 6 7]
 [2 6 8]
 [2 6 9]
 [3 4 7]
 [3 4 8]
 [3 4 9]
 [3 5 7]
 [3 5 8]
 [3 5 9]
 [3 6 7]
 [3 6 8]
 [3 6 9]]


In [5]:
# с использованием построения сетки координат методом NumPy meshgrid
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
coords = np.meshgrid(*arr, indexing='ij')
# используем вертикальное объединение массивов vstack(), и преобразуем многомерные в одномерные ravel()
result = np.vstack([matr.ravel() for matr in coords]).T # в конце транспонирование чтобы отразить по диагонали
print('Прямое произведение векторов двумерного массива', result, sep='\n')

Прямое произведение векторов двумерного массива
[[1 4 7]
 [1 4 8]
 [1 4 9]
 [1 5 7]
 [1 5 8]
 [1 5 9]
 [1 6 7]
 [1 6 8]
 [1 6 9]
 [2 4 7]
 [2 4 8]
 [2 4 9]
 [2 5 7]
 [2 5 8]
 [2 5 9]
 [2 6 7]
 [2 6 8]
 [2 6 9]
 [3 4 7]
 [3 4 8]
 [3 4 9]
 [3 5 7]
 [3 5 8]
 [3 5 9]
 [3 6 7]
 [3 6 8]
 [3 6 9]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [8]:
A = np.random.randint(7, size=(8, 3))
B = np.random.randint(7, size=(2, 2))
print(A, B, sep='\n', end='\n\n')

result = []
for i in np.arange(len(A)):
    for row in B:
        if np.isin(row, A[i]).all():
            result.append(A[i])
            
result = np.array(result)
print('Результат:', result, sep='\n')

[[2 5 4]
 [5 6 3]
 [3 2 4]
 [3 0 1]
 [4 2 6]
 [6 0 1]
 [5 1 1]
 [4 4 6]]
[[0 1]
 [5 6]]

Результат:
[[5 6 3]
 [3 0 1]
 [6 0 1]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [11]:
arr = np.random.randint(2, size=(10, 3))
print(arr)

result = []
for row in arr:
    if len(np.unique(row)) > 1:
        result.append(row)
result = np.array(result)

print('Результат:', result, sep='\n')

[[1 1 0]
 [0 0 0]
 [1 0 1]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [0 1 1]
 [0 0 1]
 [0 1 1]
 [1 0 0]]
Результат:
[[1 1 0]
 [1 0 1]
 [0 1 1]
 [0 0 1]
 [0 1 1]
 [1 0 0]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [12]:
arr = np.random.randint(3, size=(10, 2))
print(arr)
print('Результат:', np.unique(arr, axis=0), sep='\n')

[[1 2]
 [1 2]
 [0 2]
 [2 0]
 [0 0]
 [0 2]
 [2 1]
 [1 1]
 [2 0]
 [0 1]]
Результат:
[[0 0]
 [0 1]
 [0 2]
 [1 1]
 [1 2]
 [2 0]
 [2 1]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [13]:
# Python
X = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
result = 1
for x in range(len(X[0])):
    if X[x][x] != 0:
        result *= X[x][x]
print(result)

3


In [14]:
# NumPy
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
diagonal = np.diag(X)
result = np.prod(diagonal[diagonal != 0])
print(result)

3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [15]:
# Python
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
from collections import Counter
result = Counter(x) == Counter(y)
result

True

In [16]:
# Numpy
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

un_x, count_x = np.unique(x, return_counts=True)
un_y, count_y = np.unique(y, return_counts=True)

np.array_equal(un_x, un_y) and np.array_equal(count_x, count_y)

True

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [17]:
# Python
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]

elems_aft_0 = [x[i + 1] for i, value in enumerate(x[:-1]) if value == 0]

max(elems_aft_0)

5

In [18]:
# NumPy
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

mask = x == 0

np.max(x[1:][mask[:-1]])

5

* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [19]:
# Python
x = [2, 2, 2, 3, 3, 3, 5]

values = []
counts = []
curent_value = x[0]
counter = 1

for elem in x[1:]:
    if elem == curent_value:
        counter += 1
    else:
        values.append(curent_value)
        counts.append(counter)
        curent_value = elem
        counter = 1
        
values.append(curent_value)
counts.append(counter)

print(values, counts)

[2, 3, 5] [3, 3, 1]


In [20]:
# NumPy
x = np.array([2, 2, 2, 3, 3, 3, 5])

index_where_change = np.where(x[:-1] != x[1:])[0] + 1
# add first and last index
index_where_change = np.insert(index_where_change, [0, len(index_where_change)], [0, x.size])

print(x[index_where_change[:-1]], np.diff(index_where_change))

[2 3 5] [3 3 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [3]:
# Python
import random
import math
# Создадим 2 выборки
def random_points(n, d):
    return [[random.random() for _ in range(d)] for _ in range(n)]

X = random_points(100, 3)
Y = random_points(50, 3)

def euclidean_distance(X, Y):
    distances = [[0] * len(Y) for _ in range(len(X))]
    for i, x in enumerate(X):
        for j, y in enumerate(Y):
            distances[i][j] = math.dist(x, y)
    return distances

%timeit euclidean_distance(X, Y)

435 µs ± 1.51 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [4]:
# NumPy

def euclidean_distance_numpy(X, Y):
    X = np.array(X)
    Y = np.array(Y)
    return np.sqrt(np.sum((X[:, np.newaxis, :] - Y[np.newaxis, :, :]) ** 2, axis=-1))

%timeit euclidean_distance_numpy(X, Y)

134 µs ± 162 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [5]:
# SciPy

from scipy.spatial.distance import cdist

%timeit cdist(X, Y)

35.1 µs ± 95.4 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [6]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [7]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [13]:
average_calories = np.mean(calorie_stats)
print('Разница:', average_calories - 60)
print('Среднее количество у конкурентов:', average_calories)

Разница: 46.883116883116884
Среднее количество у конкурентов: 106.88311688311688


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [14]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [15]:
median_calories = np.median(calorie_stats)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [24]:
for percent in range(1, 101):
    result = np.percentile(calorie_stats, percent)
    print(f'{percent} процентиль: {result:.2f}')
    if result > 60:
        nth_percentile = result
        percentile = percent
        break
print('Наименьший процентиль превышающий 60 каллорий', percentile, 'со значением',nth_percentile)

1 процентиль: 50.00
2 процентиль: 50.00
3 процентиль: 55.60
4 процентиль: 70.00
Наименьший процентиль превышающий 60 каллорий 4 со значением 70.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [28]:
more_than_60 = calorie_stats > 60
more_calories = np.mean(more_than_60) * 100
print('Процент хлопьев в которых калорий больше 60:', f'{more_calories:.2f}%')

Процент хлопьев в которых калорий больше 60: 96.10%


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [33]:
calorie_std = np.std(calorie_stats)
print('Стандартное отклонение:',round(calorie_std, 2), f'\nЭто означает что значения разбросаны вокруг среднего значения с отклонением в {round(calorie_std, 2)}')

Стандартное отклонение: 19.36 
Это означает что значения разбросаны вокруг среднего значения с отклонением в 19.36


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [34]:
print('Мы можем использовать эти данные в первую очередь для позиционирования этого продукта(хлопьев) на рынке. \nТ.к. продукт имеет меньше каллорий чем у конкурентов, то можем спозиционировать его как более здоровый вариант.\nЭти данные также помогут нацелиться на определённые группы потребителей которые ищу такой продукт.\nТакже можно использовать информацию о калрийности для создания рекламы.\nПонимание средних значений калорийности на рынке можно использовать для определения ниши дальнейшего развития')

Мы можем использовать эти данные в первую очередь для позиционирования этого продукта(хлопьев) на рынке. 
Т.к. продукт имеет меньше каллорий чем у конкурентов, то можем спозиционировать его как более здоровый вариант.
Эти данные также помогут нацелиться на определённые группы потребителей которые ищу такой продукт.
Также можно использовать информацию о калрийности для создания рекламы.
Понимание средних значений калорийности на рынке можно использовать для определения ниши дальнейшего развития
